name: Deploy Docs

on:
  push:
    branches:
      - chore/next
    paths:
      - 'packages/docs/**'
      - .github/workflows/deploy-docs.yml
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy-docs:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Build docs
        run: pnpm -F docs build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/docs/doc_build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
