# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public
# jobs:
#   build:
#       runs-on: ubuntu-latest
#       steps:
#         - uses: actions/checkout@v3
#         - uses: pnpm/action-setup@v2
#           with:
#             node-version: 16
#         - run: npm install -g pnpm
#         - run: pnpm install
#         - run: pnpm build

#   publish-npm:
#       needs: build
#       runs-on: ubuntu-latest
#       steps:
#         - uses: actions/checkout@v2
#         - uses: actions/setup-node@v2
#           with:
#             node-version: 16
#             registry-url: https://registry.npmjs.org/
#         - run: npm ci
#         - run: npm publish
#           env:
#             NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}